//! The sample-application gallery under `examples/apps/`: one realistic checkout per
//! framework/build-tool combination, each with its structural graph committed alongside it as
//! `graph.json`.
//!
//! Every one of those files is **generated by this crate walking that application**, never written
//! by hand — regenerate them all with:
//!
//! ```text
//! UPDATE_GOLDEN=1 cargo test --test examples
//! ```
//!
//! That is the whole point of the gallery. A README claiming "this is what the graph looks like for
//! a Spring Boot app" is a claim; a `graph.json` this test regenerates and byte-compares is a fact,
//! and it fails loudly the moment the extractor's output drifts from what the documentation shows.
//! The goldens under `tests/golden/` do the same job for the minimal per-language fixtures; these do
//! it for checkouts shaped like real projects, with build files, nested package directories, and
//! framework idioms the small fixtures deliberately leave out.
//!
//! Each app additionally carries a named assertion below saying what it exists to demonstrate — the
//! part a byte-comparison cannot express. A golden proves the output is *stable*; those assertions
//! prove it is *the point*.

use std::path::PathBuf;

use lci_codegraph::{Graph, WalkOptions, walk_checkout};

fn app_root(name: &str) -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("examples/apps")
        .join(name)
}

/// The committed graph for `app` lives inside the app's own directory, next to its source — so a
/// reader browsing the sample never has to go looking somewhere else for its output.
fn graph_path(name: &str) -> PathBuf {
    app_root(name).join("graph.json")
}

/// Walk the sample app and either (`UPDATE_GOLDEN=1`) write its `graph.json`, or assert the walk
/// still matches the committed one exactly. Same contract as `tests/language_goldens.rs`.
fn assert_matches_graph(app: &str) -> Graph {
    let options = WalkOptions::builder().build_graph(true).build();
    let out = walk_checkout(&app_root(app), &options)
        .unwrap_or_else(|e| panic!("walk sample app {app}: {e}"));
    let actual = serde_json::to_string_pretty(&out.graph).expect("graph serialises");

    let path = graph_path(app);
    if std::env::var("UPDATE_GOLDEN").is_ok() {
        std::fs::write(&path, format!("{actual}\n")).unwrap();
        eprintln!("wrote {}", path.display());
        return out.graph;
    }

    let expected = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!(
            "read {} ({e}); regenerate with UPDATE_GOLDEN=1 cargo test --test examples",
            path.display()
        )
    });
    assert_eq!(
        actual.trim(),
        expected.trim(),
        "the graph for examples/apps/{app} drifted from its committed graph.json; if intended, \
         regenerate with UPDATE_GOLDEN=1 cargo test --test examples"
    );
    out.graph
}

// ── Small query helpers, so each assertion below reads as the claim it is making ────────────────

fn node_ids_starting_with<'g>(g: &'g Graph, prefix: &str) -> Vec<&'g str> {
    let mut ids: Vec<&str> = g
        .nodes
        .iter()
        .map(|n| n.node_id.as_str())
        .filter(|id| id.starts_with(prefix))
        .collect();
    ids.sort_unstable();
    ids
}

fn calls_from<'g>(g: &'g Graph, source_label: &str) -> Vec<&'g str> {
    let sources: Vec<&str> = g
        .nodes
        .iter()
        .filter(|n| n.label == source_label)
        .map(|n| n.node_id.as_str())
        .collect();
    let mut targets: Vec<&str> = g
        .edges
        .iter()
        .filter(|e| e.relation == "calls" && sources.contains(&e.source.as_str()))
        .map(|e| e.target.as_str())
        .collect();
    targets.sort_unstable();
    targets
}

fn has_cross_file_call(g: &Graph) -> bool {
    g.edges.iter().any(|e| {
        e.relation == "calls"
            && match (
                g.nodes.iter().find(|n| n.node_id == e.source),
                g.nodes.iter().find(|n| n.node_id == e.target),
            ) {
                (Some(a), Some(b)) => a.source_file != b.source_file,
                _ => false,
            }
    })
}

/// Invariants every emitted graph must hold, regardless of language or framework — the same ones
/// `tests/container_repos.rs` asserts against real-world checkouts, applied here to inputs we
/// control so a violation points at a specific sample rather than at someone else's repository.
fn assert_graph_invariants(g: &Graph, app: &str) {
    let ids: Vec<&str> = g.nodes.iter().map(|n| n.node_id.as_str()).collect();
    let mut sorted = ids.clone();
    sorted.sort_unstable();
    let before = sorted.len();
    sorted.dedup();
    assert_eq!(before, sorted.len(), "{app}: duplicate node_ids");

    for e in &g.edges {
        assert!(
            ids.contains(&e.source.as_str()),
            "{app}: edge source {} is not an emitted node",
            e.source
        );
        assert!(
            ids.contains(&e.target.as_str()),
            "{app}: edge target {} is not an emitted node",
            e.target
        );
    }
    for n in &g.nodes {
        assert!(
            n.start_line >= 1,
            "{app}: node {} has start_line {}",
            n.node_id,
            n.start_line
        );
    }
}

// ── Spring Boot, Maven, Java ────────────────────────────────────────────────────────────────────

#[test]
fn spring_boot_maven_java_graph_matches_its_committed_graph_json() {
    let g = assert_matches_graph("spring-boot-maven-java");
    assert_graph_invariants(&g, "spring-boot-maven-java");
}

#[test]
fn spring_boot_maven_java_composes_class_and_method_level_route_paths() {
    // The class-level `@RequestMapping("/api/orders")` never appears joined to a method-level
    // suffix anywhere in the source — composing them is the work. None of these five strings is
    // greppable in the app.
    let g = assert_matches_graph("spring-boot-maven-java");
    assert_eq!(
        node_ids_starting_with(&g, "route:"),
        vec![
            "route:DELETE:/api/orders/{id}",
            "route:GET:/api/orders",
            "route:GET:/api/orders/by-customer/{email}",
            "route:GET:/api/orders/{id}",
            "route:POST:/api/orders",
        ]
    );
}

#[test]
fn spring_boot_maven_java_feign_call_resolves_to_the_service_boundary() {
    // `shippingClient.requestPickup(...)` leaves this repository entirely. The honest target is the
    // boundary marker, not a symbol — the implementation is in another codebase that is not
    // checked out here and cannot be read no matter how carefully the diff is reviewed.
    let g = assert_matches_graph("spring-boot-maven-java");
    assert_eq!(
        node_ids_starting_with(&g, "service:"),
        vec!["service:shipping-service"]
    );
    assert!(
        calls_from(&g, "create()").contains(&"service:shipping-service"),
        "OrderServiceImpl.create must call the external service node"
    );
}

#[test]
fn spring_boot_maven_java_resolves_a_declared_derived_query_but_not_an_inherited_one() {
    // The honest limit of a syntactic extractor, pinned so it cannot be quietly overstated later.
    //
    // `findByCustomerEmail` is DECLARED in OrderRepository, so the Spring Data carve-out keeps it a
    // valid call target even though it has no body anywhere (Spring generates one at runtime).
    // `save`/`deleteById` are INHERITED from JpaRepository: they are declared in a dependency's
    // source, not this checkout's, so there is no node to resolve to and no edge is invented.
    let g = assert_matches_graph("spring-boot-maven-java");
    let labels: Vec<&str> = g.nodes.iter().map(|n| n.label.as_str()).collect();

    assert!(labels.contains(&"findByCustomerEmail()"));
    assert!(
        calls_from(&g, "findByCustomerEmail()")
            .iter()
            .any(|t| t.contains("OrderRepository.java")),
        "the declared derived query must resolve into the repository"
    );
    assert!(
        !labels.contains(&"save()") && !labels.contains(&"deleteById()"),
        "inherited JpaRepository methods exist in no source file here, so they must not be nodes"
    );
}

// ── Spring Boot, Gradle, Java ───────────────────────────────────────────────────────────────────

#[test]
fn spring_boot_gradle_java_graph_matches_its_committed_graph_json() {
    let g = assert_matches_graph("spring-boot-gradle-java");
    assert_graph_invariants(&g, "spring-boot-gradle-java");
}

#[test]
fn spring_boot_gradle_java_covers_every_mapping_annotation_argument_shape() {
    // This app exists to exercise the annotation forms the Maven one does not: `path =` and
    // `value =` named arguments, a bare `@RequestMapping(method = ...)`, an array of paths on one
    // handler, and a `@Controller` with no class-level prefix at all.
    let g = assert_matches_graph("spring-boot-gradle-java");
    assert_eq!(
        node_ids_starting_with(&g, "route:"),
        vec![
            "route:GET:/admin/inventory",
            "route:GET:/admin/stock",
            "route:GET:/api/stock/{sku}",
            "route:HEAD:/api/stock/health",
            "route:PATCH:/api/stock/{sku}/reserve",
            "route:PUT:/api/stock/{sku}",
        ],
        "one handler annotated with an array of two paths must yield two route nodes"
    );
}

// ── Keycloak SPI, Java, no Spring ───────────────────────────────────────────────────────────────

#[test]
fn keycloak_spi_java_graph_matches_its_committed_graph_json() {
    let g = assert_matches_graph("keycloak-spi-java");
    assert_graph_invariants(&g, "keycloak-spi-java");
}

#[test]
fn keycloak_spi_java_produces_no_framework_nodes_at_all() {
    // Java, wired by a factory and a `META-INF/services` file rather than by annotations. The
    // Spring pass must stay completely silent here — this is the negative case proving framework
    // extraction is gated on real content, not on "the file is Java".
    let g = assert_matches_graph("keycloak-spi-java");
    assert!(node_ids_starting_with(&g, "route:").is_empty());
    assert!(node_ids_starting_with(&g, "service:").is_empty());
    assert!(
        has_cross_file_call(&g),
        "plain Java resolution must still work with no framework involved"
    );
}

// ── Axum, Rust ──────────────────────────────────────────────────────────────────────────────────

#[test]
fn axum_service_rust_graph_matches_its_committed_graph_json() {
    let g = assert_matches_graph("axum-service-rust");
    assert_graph_invariants(&g, "axum-service-rust");
    assert!(has_cross_file_call(&g));
}

// ── The languages with no graph extractor ───────────────────────────────────────────────────────

#[test]
fn spring_boot_gradle_kotlin_produces_an_empty_graph_because_kotlin_has_no_extractor() {
    // Deliberately committed as an EMPTY graph, not omitted from the gallery.
    //
    // There is no Kotlin grammar in this crate, and `.kt` is not even in `lang::from_path`'s
    // extension fallback, so every Kotlin file is skipped outright — not chunked, not parsed,
    // absent from the graph. A Kotlin Spring Boot service is an extremely common thing to point a
    // code-intelligence tool at, and someone will try it; a committed empty graph answers "does
    // this work on my Kotlin service?" honestly and immediately, and gives whoever adds the grammar
    // a ready-made fixture whose expected output is already wired up.
    let g = assert_matches_graph("spring-boot-gradle-kotlin");
    assert!(
        g.nodes.is_empty() && g.edges.is_empty(),
        "Kotlin has no graph extractor today; this must stay empty until one is added, at which \
         point this test is the thing that tells you the gap closed: {g:?}"
    );
}

// ── The other tags-driven languages ─────────────────────────────────────────────────────────────

#[test]
fn nestjs_service_typescript_graph_matches_its_committed_graph_json() {
    // TypeScript resolves through the same tags path as Java, but WITHOUT framework awareness:
    // NestJS's `@Controller`/`@Get` decorators are structurally similar to Spring's annotations and
    // are deliberately not extracted. Route nodes are Spring-only today, and this app is what keeps
    // that scope statement honest rather than aspirational.
    let g = assert_matches_graph("nestjs-service-typescript");
    assert_graph_invariants(&g, "nestjs-service-typescript");
    assert!(has_cross_file_call(&g));
    assert!(
        node_ids_starting_with(&g, "route:").is_empty(),
        "NestJS decorators must NOT produce route nodes — the framework pass is Spring-only"
    );
}

#[test]
fn fastapi_service_python_graph_matches_its_committed_graph_json() {
    // Same point as the NestJS app, for Python: `@app.get(...)` is not extracted as a route.
    let g = assert_matches_graph("fastapi-service-python");
    assert_graph_invariants(&g, "fastapi-service-python");
    assert!(has_cross_file_call(&g));
    assert!(node_ids_starting_with(&g, "route:").is_empty());
}
